name: trivvo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  phosphor_flutter: ^2.1.0
  riverpod_annotation: ^2.6.1
  skeletonizer: ^2.1.0+1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - .env
